language: php
sudo: required
dist: trusty
php:
  - 7.4
before_script:
  - cd laravel-json-api
  - composer self-update --2
  - composer update
  - composer install --no-interaction
  - cd ./vue-material-dashboard
  - npm run dev
script:
  - cd laravel-json-api
  - vendor/bin/phpunit
  - php artisan code:analyse
deploy:
  skip_cleanup: true
  provider: script
  script: vendor/bin/dep deploy
  on:
    branch: master
