language: php
sudo: required
dist: trusty
php:
  - 7.2
before_script:
  - cd laravel-json-api
  - composer self-update
  - composer install --no-interaction
script:
  - vendor/bin/phpunit
  - php artisan code:analyse
deploy:
  skip_cleanup: true
  provider: script
  script: vendor/bin/dep deploy
  on:
    branch: master
