jobs:
  include:
    - language: php
      sudo: required
      dist: trusty
      php:
        - 7.4
      before_script:
        - cd laravel-json-api
        - composer self-update --2
        - composer update
        - composer install --no-interaction
    - language: node_js
      node_js:
        - "node"
      cache: npm
      before_script:
        - cd vue-material-dashboard
        - npm install -g @vue/cli
