language: php
sudo: required
dist: trusty
php:
  - 7.3
before_script:
  - cd laravel-json-api
  - composer self-update --2
  - composer install --no-interaction
  - cd laradock
  - sudo docker-compose up -d nginx mysql phpmyadmin redis workspace
  - cd ./vue-material-dashboard
  - npm run dev
script:
  - laravel-json-api/vendor/bin/phpunit
  - php artisan code:analyse
deploy:
  skip_cleanup: true
  provider: script
  script: vendor/bin/dep deploy
  on:
    branch: master
